### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by traversaro**
Fixes:
* I was passing the docker image name also to `runs-on` parameter, resulting in the job waiting forever.
* Furthermore, I was not passing `-y` to `apt-get install`.
* Furthermore, on 20.04 the tzdata was made the install hang, see https://github.com/ami-iit/meshcat-cpp/pull/5#issuecomment-1489908674
* We also a conda CI problem, that we workarounded, see https://github.com/robotology/robotology-superbuild/issues/1375 for details

### CODE REVIEW

**Comment by GiulioRomualdi** [comment]
macOS fails with
```
/Users/runner/miniconda3/envs/test/include/boost/container_hash/hash.hpp:132:33: error: no template named 'unary_function' in namespace 'std'; did you mean '__unary_function'?
        struct hash_base : std::unary_function<T, std::size_t> {};
```

As explained in https://github.com/Microsoft/cpprestsdk/issues/954 `unary_function` was removed in C++17

**Comment by traversaro** [comment]
Ubuntu 20.04 is not passing as it hangs on:
~~~
Setting up ninja-build (1.10.0-1build1) ...
Setting up libkrb5support0:amd64 (1.17-6ubuntu4.3) ...
Setting up libsasl2-modules-db:amd64 (2.1.27+dfsg-2ubuntu0.1) ...
Setting up tzdata (2022g-0ubuntu0.20.04.1) ...
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
Configuring tzdata
------------------

Please select the geographic area in which you live. Subsequent configuration
questions will narrow this down by presenting a list of cities, representing
the time zones in which they are located.

  1. Africa      4. Australia  7. Atlantic  10. Pacific  13. Etc
  2. America     5. Arctic     8. Europe    11. SystemV
  3. Antarctica  6. Asia       9. Indian    12. US
Geographic area: 
~~~

**Comment by traversaro** [comment]
We need this: https://github.com/robotology/robotology-superbuild/blob/2cdc52d76414b6a0de56ced1945a67741cb42271/.ci/install_debian.sh#L6 .

**Comment by traversaro** [comment]
> macOS fails with
> 
> ```
> /Users/runner/miniconda3/envs/test/include/boost/container_hash/hash.hpp:132:33: error: no template named 'unary_function' in namespace 'std'; did you mean '__unary_function'?
>         struct hash_base : std::unary_function<T, std::size_t> {};
> ```
> 
> As explained in [microsoft/cpprestsdk#954](https://github.com/microsoft/cpprestsdk/issues/954) `unary_function` was removed in C++17

That is tracked in https://github.com/robotology/robotology-superbuild/issues/1375, I added a workaround also for that.

**Comment by traversaro** [comment]
Ok, all CI is green, probably we can just squash with merge as it is just a bunch of CI workarounds.

**Comment by traversaro** [comment]
(By the way: Ubuntu 20.04 is happy with our use of C++20 : ) )

**Pull request merged**
